package atm.pkginterface;

import java.awt.*;

public class ATM extends javax.swing.JFrame {
    private ATMInterface atm;
    public ATM() {
        initComponents();
        BankAccount account=new BankAccount(1);
        atm=new ATMInterface(account);
    }
    private void removeComponents(){    //this is used to remove the components after successful withdraw,deposit and balance check
        lblmessage1.setVisible(false);
        lblamt.setVisible(false);
        txtamt.setVisible(false);
        btndeposit.setVisible(false);
        btnwithdraw.setVisible(false);
        btngetbalance.setVisible(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btndeposit = new javax.swing.JButton();
        btngetbalance = new javax.swing.JButton();
        btnwithdraw = new javax.swing.JButton();
        lblmessage1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        lblresult = new javax.swing.JLabel();
        txtamt = new javax.swing.JTextField();
        lblamt = new javax.swing.JLabel();
        lblmessage = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Welcome to the ATM !!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btndeposit.setBackground(new java.awt.Color(0, 102, 255));
        btndeposit.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btndeposit.setForeground(new java.awt.Color(255, 255, 255));
        btndeposit.setText("Deposit");
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });

        btngetbalance.setBackground(new java.awt.Color(0, 102, 255));
        btngetbalance.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btngetbalance.setForeground(new java.awt.Color(255, 255, 255));
        btngetbalance.setText("Check Balance");
        btngetbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetbalanceActionPerformed(evt);
            }
        });

        btnwithdraw.setBackground(new java.awt.Color(0, 102, 255));
        btnwithdraw.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnwithdraw.setForeground(new java.awt.Color(255, 255, 255));
        btnwithdraw.setText("Withdraw");
        btnwithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwithdrawActionPerformed(evt);
            }
        });

        lblmessage1.setBackground(new java.awt.Color(204, 204, 204));
        lblmessage1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblmessage1.setForeground(new java.awt.Color(51, 153, 255));
        lblmessage1.setText("Welcome to the ATM !!");

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ATM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(210, 210, 210))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, Short.MAX_VALUE)
        );

        btnexit.setBackground(new java.awt.Color(0, 102, 255));
        btnexit.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        lblresult.setBackground(new java.awt.Color(204, 204, 204));
        lblresult.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblresult.setForeground(new java.awt.Color(51, 153, 255));
        lblresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblamt.setBackground(new java.awt.Color(204, 204, 204));
        lblamt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblamt.setForeground(new java.awt.Color(51, 153, 255));
        lblamt.setText("Enter the Amount:");

        lblmessage.setBackground(new java.awt.Color(204, 204, 204));
        lblmessage.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblmessage.setForeground(new java.awt.Color(51, 153, 255));
        lblmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblamt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtamt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnwithdraw)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addComponent(btngetbalance)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(lblmessage1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblresult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblmessage, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblmessage1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblamt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblresult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnwithdraw)
                    .addComponent(btngetbalance)
                    .addComponent(btndeposit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnexit))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed
       //it is used to print the result and the message after successful and unsuccessful completion of withdrawl
        try{
            double amount=Double.parseDouble(txtamt.getText());
            if(atm.deposit(amount)){
                lblresult.setText("Amount Deposited Successfully!!!!");
                lblmessage.setText("Thank You for using the ATM !!!");
                removeComponents();
            }
            else{
                lblresult.setText("Invalid Amount");
                lblresult.setForeground(Color.red);
                txtamt.setText("");
            }
        }
        catch(NumberFormatException e){
            lblresult.setText("Please enter a valid amount");
            lblresult.setForeground(Color.red);
        }
    }//GEN-LAST:event_btndepositActionPerformed

    private void btngetbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetbalanceActionPerformed
        //it is used to print the result and the message after showing balance
        lblresult.setText("Current Balance: Rs."+atm.getbalance());
        removeComponents();
        lblmessage.setText("Thank You for using the ATM !!!");
    }//GEN-LAST:event_btngetbalanceActionPerformed

    private void btnwithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwithdrawActionPerformed
        //it is used to print the result and the message after successful and unsuccessful completion of depositing
        try{
            double amount=Double.parseDouble(txtamt.getText());
            if(atm.withdraw(amount)){
                lblresult.setText("Amount Withdrawn Successfully!!!!");
                lblmessage.setText("Thank You for using the ATM !!!");
                removeComponents();
            }
            else{
                lblresult.setText("Insufficient Balance or Invalid Amount");
                lblresult.setForeground(Color.red);
                txtamt.setText("");
            } 
        }
        catch(Exception e){
            lblresult.setText("Please enter a valid amount");
            lblresult.setForeground(Color.red);
            txtamt.setText("");
        }
    }//GEN-LAST:event_btnwithdrawActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
       //to exit the application
        System.exit(1);
    }//GEN-LAST:event_btnexitActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeposit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btngetbalance;
    private javax.swing.JButton btnwithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblamt;
    private javax.swing.JLabel lblmessage;
    private javax.swing.JLabel lblmessage1;
    private javax.swing.JLabel lblresult;
    private javax.swing.JTextField txtamt;
    // End of variables declaration//GEN-END:variables
}
